# Generated by Django 4.2.9 on 2024-02-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('text', models.CharField(max_length=50)),
                ('pred', models.CharField(max_length=50)),
                ('uid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
