# Generated by Django 4.2.9 on 2024-02-26 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_sentiment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentiment',
            old_name='uid',
            new_name='id',
        ),
    ]
