# Generated by Django 4.2.9 on 2024-03-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_sentiment_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentiment',
            old_name='id',
            new_name='sentiment_id',
        ),
    ]
